# Generated by Django 5.1.6 on 2025-03-05 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reproductive_status', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('entry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_date', models.DateField()),
                ('disease_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.cow')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateTimeField()),
                ('rectal_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('heart_rate', models.IntegerField()),
                ('respiration_rate', models.IntegerField()),
                ('rumination', models.DecimalField(decimal_places=1, max_digits=3)),
                ('treatment_status', models.CharField(default='Not Treated', max_length=20)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_date', models.DateField()),
                ('dry_matter_intake', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_interval', models.IntegerField()),
                ('service_period', models.IntegerField()),
                ('conception_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('mouth_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('treatment_status', models.CharField(default='Not Treated', max_length=20)),
                ('health_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.healthcheck')),
            ],
        ),
    ]
