# Generated by Django 5.1.6 on 2025-03-20 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_processedmilk_cow_created_at_cow_lactation_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.farmer'),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='checkup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
