# Generated by Django 5.1.6 on 2025-03-27 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_cow_farmer_alter_healthcheck_checkup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasehistory',
            name='symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.symptom'),
        ),
    ]
