# Generated by Django 5.1.6 on 2025-03-27 04:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_diseasehistory_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='health_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.healthcheck'),
        ),
    ]
