# Generated by Django 5.1.6 on 2025-04-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_diseasehistory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='body_temperature',
        ),
        migrations.AlterModelTable(
            name='cow',
            table='cows',
        ),
        migrations.AlterModelTable(
            name='diseasehistory',
            table='disease_history',
        ),
        migrations.AlterModelTable(
            name='healthcheck',
            table='health_check',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='reproduction',
            table='reproduction',
        ),
        migrations.AlterModelTable(
            name='symptom',
            table='symptom',
        ),
    ]
